name: artline_app
description: Artline Sample app.
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker:
  path_provider:
  http:
  flutter_image_compress:
  intl:
  loader_overlay:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
